/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cz.a7b36usi.sklad.gui.users;

import java.util.Arrays;

import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataListener;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import cz.a7b36usi.sklad.BO.UserRole;
import cz.a7b36usi.sklad.Controller.ifaces.IUsersController;
import cz.a7b36usi.sklad.DTO.UserDTO;
import cz.a7b36usi.sklad.Service.IUserService;
import cz.a7b36usi.sklad.gui.users.ifaces.IUserGUI;

/**
 *
 * @author Vojta
 */
@Component
public class UserGUI extends javax.swing.JFrame implements IUserGUI {

	
	@Autowired
	private IUsersController userController;
	
	private ComboBoxModel roleModel;
	
	private UserDTO user;
	
    /**
     * Creates new form User
     */
    public UserGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbRole = new javax.swing.JComboBox<UserRole>();
        tbName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tbPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbPasswordAgain = new javax.swing.JPasswordField();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setResizable(false);

        jLabel1.setText("Jméno");

        jLabel2.setText("Oprávnění");

        jLabel3.setText("Nové heslo");

        jLabel4.setText("Opakovat heslo");

        btnSave.setText("Uložit");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClose.setText("Storno");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbPassword)
                            .addComponent(cbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbName)
                            .addComponent(tbPasswordAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tbPasswordAgain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    	
    	
    	if(tbPassword.getPassword().length > 0){
    		if(!Arrays.equals(tbPassword.getPassword(), tbPasswordAgain.getPassword())){
    			JOptionPane.showMessageDialog(null, "Hesla se neshodují");
    			return;
    		}
    	}
    	
    	if(tbName.getText().isEmpty()){
    		JOptionPane.showMessageDialog(null, "Jméno musí být vyplněné");
			return;
    	}
    	
    	UserRole acl = UserRole.values()[cbRole.getSelectedIndex()];
    	
    	
    	if(user != null){
	    	user.setUsername(tbName.getText());
	    	
	    	user.setAcl(acl);
	    	
	    	userController.updateUser(user);
	    	
	    	if(tbPassword.getPassword().length > 0){
	    		userController.updatePassword(user, tbPassword.getPassword());
	    	}
    	}else{
    		if(tbPassword.getPassword().length == 0){
    			JOptionPane.showMessageDialog(null, "Heslo musí být vyplněné");
    			return;
    		}
    		userController.createUser(tbName.getText(), tbPassword.getPassword(), acl);
    	}
    	setVisible(false);
    	
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
    	setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<UserRole> cbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tbName;
    private javax.swing.JPasswordField tbPassword;
    private javax.swing.JPasswordField tbPasswordAgain;
    // End of variables declaration//GEN-END:variables

    public void setUser(UserDTO user) {
    	
    	this.user = user;
    	
    	roleModel = new ComboBoxModel<UserRole>() {
    		UserRole selected = null;
			public int getSize() {
				return UserRole.values().length;
			}

			public UserRole getElementAt(int index) {
				return UserRole.values()[index];
			}

			public void addListDataListener(ListDataListener l) {}

			public void removeListDataListener(ListDataListener l) {}

			public void setSelectedItem(Object anItem) {
				selected = (UserRole)anItem;
			}

			public UserRole getSelectedItem() {
				return selected;
			}
    	};
    	
    	cbRole.setModel(roleModel);
    	
    	if(user != null){
	    	tbName.setText(user.getUsername());
	    	
	    	int i = 0;
	    	for(UserRole r : UserRole.values()){
	    		if(r == user.getAcl()){
	    			cbRole.setSelectedIndex(i);
	    			break;
	    		}
	    		i++;
	    	}
    	}else{
    		tbName.setText("");
    		cbRole.setSelectedIndex(0);
    	}
    	
    }
}
